name: check-broken-links
on: [push]

jobs:
  check-broken-links:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Ruby
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: 3.2
      - name: Setup Rubygems, Bundler, jekyll
        run: | 
          gem update --system --no-document
          gem update bundler --no-document
          gem install html-proofer -v 3.4.0
          gem install jekyll bundler
          bundle install
      - name: Build jekyll website with drafts
        run: bundle exec jekyll build --drafts
      - name: Check for broken links
        run: |
          bundle exec htmlproofer --log-level :debug _site &> links.log
        continue-on-error: true
      - name: Archive log links
        uses: actions/upload-artifact@v3
        with:
          name: links-check.log
          path: links.log